version: "3"

vars:
    GOOS: "{{default OS .GOOS}}"
    MVNW: '{{if eq .GOOS "windows"}}cmd /c mvnw.cmd{{else}}./mvnw{{end}}'
    DC_DIR: "deployment/docker-compose"
    APP_DC_FILE: "{{.DC_DIR}}/app.yml"
    SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
    default:
        cmds:
            - task: test
    test:
        cmds:
            - "{{.MVNW}} clean verify"

    build:
        cmds:
            - "{{.MVNW}} spring-boot:build-image -DskipTests"

    start:
        deps: [build]
        cmds:
            - "docker compose -f {{.APP_DC_FILE}} up -d"

    stop:
        cmds:
            - "docker compose -f {{.APP_DC_FILE}} stop"
            - "docker compose -f {{.APP_DC_FILE}} rm -f"

    restart:
        cmds:
            - task: stop
            - task: sleep
            - task: start

    sleep:
        vars:
            DURATION: "{{default 5 .DURATION}}"
        cmds:
            - "{{.SLEEP_CMD}} {{.DURATION}}"
