name: "clubcompass-app"
services:
    clubcompass-db:
        image: postgres:16-alpine
        container_name: clubcompass-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - "15432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    memory: 700m
    clubcompass-web:
        image: ansbeno/clubcompass-web
        container_name: clubcompass-web
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - DB_URL=jdbc:postgresql://clubcompass-db:5432/postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres

        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            clubcompass-db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 700m
